updates
1. myCraft/log.txt need to update since it fails on
2. myMainStage need to fix icon = "S-2116i"

org.jsoup.HttpStatusException: HTTP error fetching URL. Status=404, URL=https://tos.fandom.com/zh/wiki/%E6%A3%AE%E4%B9%8B%E5%B1%8F%E6%81%AF%E9%BE%8D%E7%AC%A6